# Platform.sh Project Initialization Template
#
# This file defines settings and workflow modifications that allow a git
# repository to be deployed to Platform.sh and its white-label partners. A
# project template can be a fully functioning ready-made application or a
# quick-start point for custom development work.
#
# It contains elements that affect the behaviour upon the initialisation of
# a new project (for example minimal plan sizes) as well as elements that
# allow Platform.sh to present it in a user interface (such as the description
# of the project, tags, an icon etc.).
#
# Once provisioned this file has no effects on the running project.  You
# are free to remove it.

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/wagtail
  # The human-readable name of the template.
  name: Wagtail
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: |
      <p>This template builds the Wagtail CMS on Platform.sh, using the gunicorn application runner.</p>
      <p>Wagtail is a web CMS built using the Django framework for Python.</p>
  # A list of tags associated with the template.
  tags:
  - Python
  - Framework
  - CMS
  # An image URI (either base64-encoded or a URL) representing the template.
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAyNSIgaGVpZ2h0PSIyNTAwIiB2aWV3Qm94PSIwIDAgMjU2IDMxNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCI+PHBhdGggZD0iTTIxNC43NSA0Ni4yNWE2LjUgNi41IDAgMSAwIDAtMTMgNi41IDYuNSAwIDAgMCAwIDEzem04LjI1IDU2cy04LjI1LTQxLjUtNjIuMjUtMzAuMjVjLTUuNS0xOC43NS00LjUtMzIuNSA3LjUtNDUuMjVDMTg0LjUgOS41IDIxMCAxOSAyMTAgMTlWNC43NUMyMDEgLjc1IDE5Mi41IDAgMTgzIDBjLTM0Ljc1IDAtNTQgMjYtNjIuMjUgNDMuNUwyMyAyMjMuMjUgNTAuNSAyMTggMCAzMTUuNWwzNS4yNS02LjI1IDI3LTc2Ljc1Yzc2LjUgMCAxNzQuNS0yNy41IDE2MC43NS0xMzAuMjV6bTMzLTM0Ljc1bC0yMS41LTIwLjc1LTE3IDIwLjc1SDI1NnpNNzUgMjEwLjI1czIuNS0uNSA3LTEuNSAxMC43NS0yLjUgMTguMjUtNC41YzMuNzUtMSA3Ljc1LTIuMjUgMTItMy43NXM4Ljc1LTMgMTMtNWM0LjUtMS43NSA5LTQgMTMuNS02LjVzOC43NS01LjI1IDEyLjc1LTguNWMxLS43NSAyLTEuNSAzLTIuNWwzLTIuNWMxLjc1LTEuNzUgMy43NS0zLjUgNS41LTUuNSAxLjc1LTEuNzUgMy4yNS0zLjc1IDQuNzUtNS43NWwyLjI1LTMgMS0xLjUgMS0xLjVjLjUtMSAxLjI1LTIgMS43NS0zczEtMiAxLjc1LTNsLjc1LTEuNS43NS0xLjVjLjUtMSAxLTIgMS4yNS0zbDIuMjUtNmMuNS0yIDEuMjUtNCAxLjc1LTUuNzVzLjc1LTMuNzUgMS4yNS01LjI1Yy4yNS0xLjc1LjUtMy4yNS43NS01IC4yNS0xLjUuNS0zIC41LTQuMjUuMjUtMS4yNS4yNS0yLjUuNS0zLjc1LjI1LTQuNS4yNS03IC4yNS03bDQgLjI1cy0uMjUgMi43NS0uNSA3LjI1Yy0uMjUgMS4yNS0uMjUgMi41LS41IDMuNzUtLjI1IDEuNS0uMjUgMy0uNzUgNC41LS4yNSAxLjUtLjc1IDMuMjUtMSA1LS41IDEuNzUtMSAzLjUtMS41IDUuNXMtMS4yNSAzLjc1LTIgNmMtLjc1IDItMS41IDQtMi41IDYuMjVsLTEuNSAzLS43NSAxLjUtLjc1IDEuNWMtLjUgMS0xLjI1IDItMS43NSAzLjI1LS43NSAxLTEuMjUgMi0yIDMtLjI1LjUtLjc1IDEtMSAxLjVsLTEgMS41LTIuMjUgM2MtMS43NSAyLTMuMjUgNC01LjI1IDUuNzUtMS43NSAyLTMuNzUgMy41LTUuNzUgNS41bC0zIDIuNWMtMSAuNzUtMiAxLjUtMy4yNSAyLjI1LTQuMjUgMy04Ljc1IDUuNzUtMTMuMjUgOC4yNS00LjUgMi4yNS05LjI1IDQuNS0xMy43NSA2LjI1cy05IDMuMjUtMTMuMjUgNC41LTguMjUgMi41LTEyLjI1IDMuMjVjLTcuNSAxLjc1LTE0IDMuMjUtMTguNSA0LTQgMS41LTYuNSAyLTYuNSAyeiIvPjwvc3ZnPg==
  
  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Apps & Services"
      content: "Python 3.7<br/>PostgreSQL 10"

# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: git://github.com/platformsh/template-wagtail.git@master
  config: null
  files: []
  profile: Wagtail
