## Project behavior schema

# Allows products and project creation to define
# various settings and workflow modifications

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/django2
  # The human-readable name of the template.
  name: Django 2
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: Django is a Python-based free and open-source web framework
  # A list of tags associated with the template.
  tags:
  - Python
  - Framework
  # An image URI (either base64-encoded or a URL) representing the template.
  image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAMAUExURQAAAImalTpVTdne3Bw8Mg4wJv7+/mB2b7K8uREyKBg4LgAgFShGPXOHgUxkXZ6sqMTMyggpH+To5lRsZert7AYoHjBNRH+Ri87U0gosIrvFwpCfmqm1sltyayA+NW2BfD9aUjZSSd7j4Wh9dyRCOQIlGu3w79LY1peloVdvaKSwrE9nYHmMhsjPzC1KQoaXkUZgWMDJxgcqIGV6dI6emRAwJ624tebp6Gp+eLfBvpKhnHGEfuHl5CpIP6GuqoGTjdXb2dvh33aJg0FcVDNQR+/y8U9oYCJAN2J3cXyOicnQzgAAADMAADMAMzMAZjMAmTMAzDMA/zMzADMzMzMzZjMzmTMzzDMz/zNmADNmMzNmZjNmmTNmzDNm/zOZADOZMzOZZjOZmTOZzDOZ/zPMADPMMzPMZjPMmTPMzDPM/zP/ADP/MzP/ZjP/mTP/zDP//2YAAGYAM2YAZmYAmWYAzGYA/2YzAGYzM2YzZmYzmWYzzGYz/2ZmAGZmM2ZmZmZmmWZmzGZm/2aZAGaZM2aZZmaZmWaZzGaZ/2bMAGbMM2bMZmbMmWbMzGbM/2b/AGb/M2b/Zmb/mWb/zGb//5kAAJkAM5kAZpkAmZkAzJkA/5kzAJkzM5kzZpkzmZkzzJkz/5lmAJlmM5lmZplmmZlmzJlm/5mZAJmZM5mZZpmZmZmZzJmZ/5nMAJnMM5nMZpnMmZnMzJnM/5n/AJn/M5n/Zpn/mZn/zJn//8wAAMwAM8wAZswAmcwAzMwA/8wzAMwzM8wzZswzmcwzzMwz/8xmAMxmM8xmZsxmmcxmzMxm/8yZAMyZM8yZZsyZmcyZzMyZ/8zMAMzMM8zMZszMmczMzMzM/8z/AMz/M8z/Zsz/mcz/zMz///8AAP8AM/8AZv8Amf8AzP8A//8zAP8zM/8zZv8zmf8zzP8z//9mAP9mM/9mZv9mmf9mzP9m//+ZAP+ZM/+ZZv+Zmf+ZzP+Z///MAP/MM//MZv/Mmf/MzP/M////AP//M///Zv//mf//zP///7XZdCkAAABMdFJOUwD//////////////////////////////////////////////////////////////////////////////////////////////////wCwhjatAAADxElEQVR42u3abVfaMBQAYIEmIw5BpWFcBJzYq4AIbhhh+ILC6pT//4N2eJmS0GmRND07y/1Yj9yH0N7cJN1iMceWBViABViABViABViABViABfyzAJCCLK4S+bKIEOBUl4PNUwnmLEXViW4EwEn5y9Hls8uYdXuv4RYLEBmg6tLl6C8ADemqm+TRAXpSquMFIC9d7R1ZgAVYgAX874DYS/GN8REA7+ws+xKPWYcYBjCyt/fajnB4P79ugLGWLC6AmPd8hMQBEMAR578qgc8sGCCIFPoABDivjiujQbOcTl/lOk95NxgQTVdMEDLdctGnf40FgI9Ly9HMaGlKBYeLeo++GX8KUUWuhD91FCLAZNmnNBxAroQ1HW05sJZLaXwA9K4ojRGAhQmNE8AzRRonAJwSjRNA9gY0VoDyccYBwM5XM53eDa+vR4n0vgEAdtXsfm68TQARAdpu5ABgu0r+YhY5ECGEIN+dXuQAzCr5J7dI1mtKNwIISFClycd1u+KNACu/wAiFWUBbngJTHjCjAK4UgToyswAcyYAKNw2Qy7B/BKYBTbm7qhoHyI1IzTEOSEuf9eDEPAI3Tsz3gH8L8T4F9NH0Y8hbMqBjuhBxeZFDz1mYUtzQOBcUlOVQJcxkVNEI2FY68lOPGwUQUFvitPM6BgYAAT1xKYkcpj0ZIeBEDwhoit36eFsA5wDgBTeln7R2xf2ABcB9+WA47Aya34Lb8q7edcHu2guTvt6V0YW/HkDgjlaAUKvhewDCh3Ifebvp6hjq6wHgUr5hvE33B0AM1gKQnLyUqm68QwKw44YHAJO7mImz+R4R4LgUHqCU75LQsF0vOOu+/zgezgG/5OFKo9gcMB0E1sjtv5Xer+VnYw1j+XoTNW3VAoJXGZRSK2Xh5GHy4+65UVi8qYCH8p8TugCzzWqEzDh//HxZzzXvcvVBotWv5L+2HcDZDBXURy5+GG3nBVPEfDok02MDjkupFydGKRmQBa2AlwOB6YkFISv3l8AnZfL0IgC8uausTJG7zCxA6UYoTUT6Gs9qG129VwD5EA+BPgBAU91UC1GI9QFA3dOi9EuYAdAF4OxAzX8T5hnQBABsp1fqcyvERKAHAMj6tZX84e4AHQAO+YAJ28+GPEvdFCBYJbBfGCExAwBnGHSkmABgZgBMcG90+vH8em5CR+6Z3H74/FoeQwHI8unlNWz4/LoKESDJNk9mi5FDxgUzDmAMOE8OXLeTWefr652OCYdCG2DN/9L6XjEBICxOwEfCAizAAizAAizAAmIH/AYeZoaILuXMmgAAAABJRU5ErkJggg==
  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Apps & Services"
      content: "Python 3.7<br/>PostgreSQL 9.6"
    - heading: "Requirements"

# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: git://github.com/platformsh/template-django2.git@master
  config: null
  files: []
  profile: Django 2
