# The services of the project.
#
# Each service is an automatically provisioned, fully managed backend
#
# See https://docs.platform.sh/configuration/services.html
postgresql:
  type: postgresql:11
  disk: 256
#elasticsearch:
#  type: elasticsearch:5.4
#  disk: 256
#mysql:
#  type: mysql:10.2
#  disk: 256
#mongodb:
#  type: mongodb:3.6
#  disk: 500
#solr:
#  type: solr:6.6
#  disk: 256
#rabbitmq:
#  type: rabbitmq:3.7
#  disk: 256
#memcached:
#  type: memcached:1.4
#influxdb:
#  type: influxdb:1.3
#redis:
#  type: redis:5.0