# This file describes an application's routes. You can define as many routes as your
# application requires.
#
# See https://docs.platform.sh/configuration/routes.html

# URL template for the main route, where `{default}` is replaced by
# the Platform.sh generated environment URL or the configured domain.
"https://{default}/":
    # This route serves an application (upstream).
    type: upstream

    # Defines the upstream according to the form `<application-name>:http`,
    # where the `name` attribute from `.platform.app.yaml` is used.
    upstream: "app:http"

    # Optional route identifier; constant across all environments.
    id: "main"

    # HTTP cache configuration.
    cache:
        # Enabled (default `true`, but only if `cache` attribute is unspecified).
        enabled: true

        # List of allowed cookie names, all others are ignored. 
        cookies:
          # Used to identify a backend session when Backend User logged in.
          - 'be_typo_user'
          # Used to identify session ID when logged into TYPO3 Frontend.
          - 'fe_typo_user'
          # Default PHP session cookie.
          - 'PHPSESSID'
          # Validates sessions for System Maintenance Area.
          - 'Typo3InstallTool'
